<script setup lang="ts">
import { ref, computed } from 'vue';
import SplatViewer from '../SplatViewer.vue';
import { GaussianSplat } from "cg-vue-splat";

// 定义所有模型
const allModels = [
  // 第一组模型
  {
    id: 'model1',
    name: 'Model 5_0',
    path: '/3dgs/5_0.ksplat',
    scale: [0.05, 0.05, 0.05] as [number, number, number],
    cameraPosition: [0, 0, -6] as [number, number, number],
    group: 'group2'
  },
  {
    id: 'model2',
    name: 'Model 15_0',
    path: '/3dgs/15_0.ksplat',
    scale: [0.05, 0.05, 0.05] as [number, number, number],
    cameraPosition: [0, 0, -6] as [number, number, number],
    group: 'group2'
  },
  {
    id: 'model3',
    name: 'Model 35_0',
    path: '/3dgs/35_0.ksplat',
    scale: [0.05, 0.05, 0.05] as [number, number, number],
    cameraPosition: [0, 0, -6] as [number, number, number],
    group: 'group2'
  },
  // 第二组模型
  {
    id: 'model4',
    name: 'Model 50_0',
    path: '/3dgs/6_20.ksplat',
    scale: [0.05, 0.05, 0.05] as [number, number, number],
    cameraPosition: [0, 0, -6] as [number, number, number],
    group: 'group1'
  },
  {
    id: 'model5',
    name: 'Model 75_0',
    path: '/3dgs/0_60.ksplat',
    scale: [0.05, 0.05, 0.05] as [number, number, number],
    cameraPosition: [0, 0, -6] as [number, number, number],
    group: 'group1'
  },
  {
    id: 'model6',
    name: 'Model 100_0',
    path: '/3dgs/4_40.ksplat',
    scale: [0.05, 0.05, 0.05] as [number, number, number],
    cameraPosition: [0, 0, -6] as [number, number, number],
    group: 'group1'
  }
];

// 当前选中的模型组
const currentGroup = ref<'group1' | 'group2'>('group1');
const loadedModelsByGroup = ref<{ [key: string]: string[] }>({
  group1: [],
  group2: [],
});

const loadModel = (modelId: string) => {
  const currentLoadedModels = loadedModelsByGroup.value[currentGroup.value];
  if (!currentLoadedModels.includes(modelId)) {
    currentLoadedModels.push(modelId);
  }
};

// 切换模型组
const switchModelGroup = (group: 'group1' | 'group2') => {
  currentGroup.value = group;
};

// 布局控制
const viewerHeight = ref('350px'); // 默认高度
const viewerMinHeight = ref('350px'); // 最小高度
</script>

<template>
  <!-- <div class="gs-comparison-container"> -->
    <el-divider />
    
    <el-row justify="center">
      <h1 class="section-title">3DGS Model Visualization</h1>
    </el-row>

    <el-row justify="center">
      <el-col :xs="24" :sm="22" :md="20" :lg="18" :xl="16">
        <p class="section-description">
          Thanks to
          <a href="https://github.com/mkkellogg/GaussianSplats3D" target="_blank">GaussianSplats3D</a>,
          we can visualize 3DGS models generated by our model. Due to network resource constraints, the 3DGS model has been cropped to a rectangular region and subjected to quality compression, resulting in a degree of visual quality degradation.
        </p>
        
        <!-- 模型组切换按钮 -->
        <div class="group-switcher">
          <el-row justify="center" class="switcher-row">
            <el-button-group>
              <el-button 
                :type="currentGroup === 'group1' ? 'primary' : 'default'"
                @click="switchModelGroup('group1')"
                size="large"
              >
              Carla-Centric
                
              </el-button>
              <el-button 
                :type="currentGroup === 'group2' ? 'primary' : 'default'"
                @click="switchModelGroup('group2')"
                size="large"
              >
                Nuscenes
              </el-button>
            </el-button-group>
          </el-row>
        </div>
        
        <!-- 大尺寸水平排列的3D查看器 -->
        <div class="viewers-container">
          <el-row :gutter="30" justify="center" align="stretch">
            <!-- 使用 v-show 避免重新加载模型 -->
            <el-col 
              v-for="model in allModels" 
              :key="model.id"
              :xs="24" 
              :sm="24" 
              :md="12" 
              :lg="8"
              class="viewer-column"
              v-show="model.group === currentGroup"
            >
              <div class="viewer-wrapper">
                <h3 class="model-title">{{ model.name }}</h3>
                <div class="viewer-box">
                  <div v-if="!loadedModelsByGroup[model.group].includes(model.id)" class="load-button-container">
                    <el-button @click="loadModel(model.id)" type="primary" size="large">Load Model</el-button>
                  </div>
                  <SplatViewer
                    v-if="loadedModelsByGroup[model.group].includes(model.id)"
                    :splat-path="model.path"
                    :splat-scale="model.scale"
                    :initial-camera-position="model.cameraPosition"
                    :enable-controls="false"
                    width="100%"
                    :height="viewerHeight"
                    aspect-ratio="9/9"
                  />
                </div>
              </div>
            </el-col>
          </el-row>
        </div>
      </el-col>
    </el-row>
  <!-- </div> -->
</template>

<style scoped>
.gs-comparison-container {
  width: 100%;
  max-width: 100%;
  padding: 0 10px;
}

.section-title {
  font-size: 2.8rem;
  font-weight: bold;
  margin-bottom: 1.5rem;
  text-align: center;
  background: linear-gradient(45deg, #409EFF, #67C23A);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.section-description {
  text-align: center;
  font-size: 1.1rem;
  margin-bottom: 2rem;
  color: var(--dark-text-primary);
}

.load-button-container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;
  min-height: v-bind(viewerMinHeight);
}

.group-switcher {
  margin: 2rem 0;
}

.switcher-row {
  margin-bottom: 2rem;
}

.viewers-container {
  width: 100%;
  margin: 0 auto;
}

.viewer-column {
  margin-bottom: 30px;
}

.viewer-wrapper {
  background: white;
  border-radius: 12px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);
  overflow: hidden;
  height: 100%;
  transition: transform 0.3s ease;
  transition: all 0.3s ease;
  opacity: 1;
}

.viewer-wrapper:hover {
  transform: translateY(-3px);
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.12);
}

.model-title {
  text-align: center;
  font-size: 1.3rem;
  font-weight: 600;
  margin: 0;
  padding: 15px 20px;
  background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
  color: #2c3e50;
  border-bottom: 1px solid #e4e7ed;
}

.viewer-box {
  padding: 0;
  min-height: v-bind(viewerMinHeight);
}

/* 添加隐藏动画 */
.viewer-column[style*="display: none"] .viewer-wrapper,
.viewer-column[style*="display: none"] {
  opacity: 0;
  transform: scale(0.95);
}

/* 响应式调整 */
@media (max-width: 1200px) {
  .section-title {
    font-size: 2.5rem;
  }
  
  .viewer-wrapper {
    margin-bottom: 20px;
  }
}

@media (max-width: 992px) {
  .section-title {
    font-size: 2.2rem;
  }
  
  .viewer-column {
    margin-bottom: 25px;
  }
}

@media (max-width: 768px) {
  .gs-comparison-container {
    padding: 0 5px;
  }
  
  .section-title {
    font-size: 2rem;
  }
  
  .section-description {
    font-size: 1rem;
    padding: 0 15px;
  }
  
  .viewer-wrapper {
    margin-bottom: 20px;
  }
  
  .model-title {
    font-size: 1.2rem;
    padding: 12px 15px;
  }
}

@media (max-width: 576px) {
  .section-title {
    font-size: 1.8rem;
  }
  
  .viewer-box {
    min-height: 300px;
  }
}

/* 超大屏幕优化 */
@media (min-width: 1400px) {
  .viewers-container {
    max-width: 1400px;
    margin: 0 auto;
  }
}

/* 确保viewer占满容器 */
:deep(.splat-viewer) {
  min-height: v-bind(viewerMinHeight);
}
</style>
